# Generated by Django 2.1 on 2018-09-05 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetails',
            fields=[
                ('adid', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('tel', models.BigIntegerField()),
                ('addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pub_date', models.DateField()),
                ('author', models.ManyToManyField(to='bm01.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=11, unique=True)),
                ('addr', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bm01.Publish'),
        ),
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bm01.AuthorDetails'),
        ),
    ]
